### ISSUE TITLE
Frage zu Sentry

### ISSUE THREAD

**Issue by IzzySoft** [Lasslos/your_schedule#1]
Aus Rainer Neugier: Ist Sentry in dieser App per Default aktiv – oder wird man vorher gefragt, ob man es "erlauben" möchte (GDPR/DSGVO-Speak: "explicit informed consent")?

**Comment by Lasslos** [comment]
Das ist Top Sigrid.
Spaß beiseite, danke für den Hinweis. Ich war mir intuitiv sicher, Crashalytics können keine personenbezogenen Daten sein, steht trotzdem in der Privacy Policy, dass ich die sammle. Wenn das doch in den consent fällt, sollte ich mal schnell ein Update machen :O

**Comment by IzzySoft** [comment]
Danke, @Lasslos! Die Frage ist aber auch: Ist das per Default aktiv – oder wird man vorher gefragt, ob es aktiviert werden darf/soll? In ersterem Fall gälte das als "Tracking" (aka "without consent") – in letzterem nicht (da Consent ja gegeben).

![image](https://github.com/Lasslos/your_schedule/assets/6781438/6d47235b-ba2c-41c3-a469-064a430a00b8)

Habe Deine App vorgestern [meinem Repo hinzugefügt](https://apt.izzysoft.de/fdroid/index/apk/eu.laslo_hauschild.your_schedule) und würde mich freuen, die "Anti-Features" Box entfernen zu können. Oh, und auf der anderen Seite kannst Du Dir gern [eine Badge aussuchen](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it), um sie neben die einsame Badge von Google Play zu platzieren und dorthin zu verlinken :smiley:

**Comment by Lasslos** [comment]
Aktuell per default, dass wird sich aber, wenn ich dazu komme, ändern. Ich verlinke den commit dann hier. Btw: Heute habe ich 1.3.14 released, wenn du möchtest, kannst du das ja in deinem Repo updaten ^^. Danke, dass du die App aufgenommen hast!

**Comment by IzzySoft** [comment]
> Aktuell per default, dass wird sich aber, wenn ich dazu komme, ändern. Ich verlinke den commit dann hier.

Prima! Bitte mit "comment" dann, damit ich eine Benachrichtigung bekomme (und das Anti-Feature wieder entferne).

> Btw: Heute habe ich 1.3.14 released, wenn du möchtest, kannst du das ja in deinem Repo updaten

Das passiert automatisch. Da läuft bei mir täglich ein Skript (per Cron), das sich darum kümmert.

> Danke, dass du die App aufgenommen hast!

Gern doch! Ist übrigens auch noch an anderer Stelle zu finden: [Stundenpläne und Schul-Organizer](https://android.izzysoft.de/applists/category/named/school_organizer) :smiley:

**Comment by Lasslos** [comment]
Consent wird ab b479f483629f05ebb5ddb392ff3674c232d02939 gefragt. Ich pushe die Version jetzt auf die internal test branch, ab v1.4.2 wird dann standardmäßig nach consent gefragt :).

**Comment by IzzySoft** [comment]
Danke! Habe vertrauensvoll das `Tracking` AntiFeature gerade entfernt.
