### ISSUE TITLE
Fragen zur App 

### ISSUE THREAD

**Issue by srt54558** [Lasslos/your_schedule#5]
Hallo,
ich finde diese Flutter App sehr cool! Leider benutzt meine Schule jedoch das DSB von Heinekingmedia. 
Ich hätte da ein paar Fragen...
-Welche Schnittstelle benutzt diese App? Also gibt es eine offene API von units oder wie verläuft es?
-Wie bist du an die Daten gekommen?

Ich würde liebend gerne auch ein Client erstellen, da der originale Client des DSB grauenhaft ist veraltet ist.

**Comment by Lasslos** [comment]
Hey, du kannst diese App sehr gerne forken und den `core` mit deinem eigenen ersetzen!

Untis selbst hat keine API. Ich habe deswegen mit einem Android Emulator, installiert über Android Studio, und dem Programm Http Toolbox die Requests angeguckt, die die Original-App macht. Dann habe ich die versendeten und empfangenen Daten in Klassen umgewandelt ([siehe hier](https://github.com/Lasslos/your_schedule/tree/main/lib/core/untis/models), die Requests sind immer in den .txt-Dateien zusammengefasst) und das Durchführen der Requests [hier](https://github.com/Lasslos/your_schedule/tree/main/lib/core/untis/requests) umgesetzt.

Der Rest ist eine Flutter-App mit Riverpod usw.

Ich habe das ganze auch ausführlich dokumentiert, und zwar in meiner Facharbeit. Da werden genau deine Fragen sehr detailliert beantwortet. Manche Hinweise zur Implementierung sind jedoch recht veraltet: 
[Facharbeit.pdf](https://github.com/Lasslos/your_schedule/files/14482164/Facharbeit.pdf)

Wenn du die App forken möchtest, würde ich dir empfehlen, den Ordner `migration_core` direkt zu entfernen, der kümmert sich nur um das Migrieren von Daten aus alten Versionen. Den Ordner `background` kannst du auch entfernen, der ist ganz neu, da ist noch nichts sinnvolles drin. Ansonsten ist der Code weitgehend sehr durchdacht, ich habe mir Mühe gegeben, nichts `quick-and-dirty` zu machen, deswegen hoffe ich, dass er dir weiterhilft.

Schreib bei Fragen gerne nochmal!
