### ISSUE TITLE
2-factor authentication

### ISSUE THREAD

**Issue by biosaat** [Lasslos/your_schedule#7]
Is there a way to use the app when 2-factor authentication is required?

**Comment by Lasslos** [comment]
Nope, not currently.

If you want to change that, feel free to PR. Unfortunately, I won't be able to implement that as I don't manage any 2FA-enabeld accounts nor do I have the spare time to do that right now.

**Comment by Jeidnx** [comment]
Another way to solve this would be to switch from passwords to secret authentication. This also has the additional benefit of being able to log into an account just by scanning a qr code from the untis website (or a printout). The implementation is fairly straightforward, i would suggest looking at other untis projects / libraries.

Some additional info regarding the qr code from the untis website (the article isn't available in english): https://help.untis.at/hc/de/articles/360010794740-Wie-lege-ich-mein-Profil-in-Untis-Mobile-an
